### PR TITLE
Add NTP setup to job servers

### PR DESCRIPTION
**Pull request by 0505gonzalez**
Applies to services that use the simpler deployment config (`workers-config.yml`)

### CODE REVIEW

**Comment by boxbag** [comment]
Doesn't AWS have an NTP server now? Otherwise LGTM

**Comment by 0505gonzalez** [comment]
@LieAlbertTriAdrian can you comment? Did I do this right?

**Comment by LieAlbertTriAdrian** [comment]
Yeah, amazon just released new NTP synchronization way with chrony https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/ (it's faster and more accurate than ntpd, AWS said). But I think it's ok to use it now. We can test and use chrony later. Our priority right now is to make sure the time is synced. @0505gonzalez

**Comment by LieAlbertTriAdrian** [comment]
LGTM

**Pull request merged**
